# Generated by Django 4.1 on 2022-08-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='vate_ratio',
            new_name='vote_ratio',
        ),
    ]
