# Generated by Django 4.1 on 2022-08-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_vate_ratio_project_vote_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_imgs',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
